# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pbkdf2"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sam Quigley"]
  s.date = "2013-09-16"
  s.description = "This implementation conforms to RFC 2898, and has been tested using the test vectors in Appendix B of RFC 3962. Note, however, that while those specifications use HMAC-SHA-1, this implementation defaults to HMAC-SHA-256. (SHA-256 provides a longer bit length. In addition, NIST has stated that SHA-1 should be phased out due to concerns over recent cryptanalytic attacks.)"
  s.email = "quigley@emerose.com"
  s.extra_rdoc_files = [
    "LICENSE.TXT",
    "README.markdown"
  ]
  s.files = [
    "LICENSE.TXT",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/pbkdf2.rb",
    "pbkdf2.gemspec",
    "spec/pbkdf2_spec.rb",
    "spec/rfc3962_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/emerose/pbkdf2-ruby"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Password-Based Key Derivation Function 2 - PBKDF2"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<rdoc>, [">= 2.4.2"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rdoc>, [">= 2.4.2"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rdoc>, [">= 2.4.2"])
  end
end

